### ISSUE TITLE
Hi, do you know how can I display my localStorage data like how you show yours in this project?

### ISSUE THREAD

**Issue by richjr93** [RichardZhang01/code-quiz#1]
Hi, I'd like to ask for help from you if you can. First of all, FYI, I have little to zero knowledge of coding.
So I actually have data in my localStorage but it is not stored in an array like yours, it has 1 value only per key. My localStorage data looks like this: 
![image](https://user-images.githubusercontent.com/68835183/202117608-34205291-d609-41a2-a990-17169dc8a646.png)

That is an example. It includes 3 different users and each user has 3 records, their wins, losses, and ties. The actual amount of user records I have right now is like thousands. I would like to display them just like your highscores display maybe only for the first 5 or 10 highest because I have a lot of users.

I'd really appreciate it if you could help. Thank you very much in advance!

**Comment by RichardZhang01** [comment]
Hi there,

This was actually one of my first apps ever, so I haven't looked or even
used vanilla HTML/CSS/JS in a while. For what you want to do, you just need
to store each of your records in an array before setting it in localstorage.
I'm not exactly sure how you're doing it, I'd have to look at your code,
but I'm guessing you're setting each individual score in local storage.
something like localstorage.setItem("sara_win", 50). Instead, you'll want
to push each of these elements into an array first. So you'd want to create
an array:

const scoresArray = JSON.parse(localstorage.getItem("scoresArray")) || [];

scoresArray will first attempt to retrieve the data with the key of
"scoresArray" (you can name the array and key whatever you want) and if it
doesn't exist, then it'll just be an empty array. Then you'll want to push
your scores each time to this array. you can do that by doing
scoresArray.push(<someone's score>). Now you can make an array that looks
something like ["sara_win, 50", "sara_lose, 30", "sara_tie, 3"] or even
[["sara_win", 50], ["sara_lose", 30], ["sara_tie", 3]]. It's really up to
you, and all you need to do to push this one value into localstorage is:

localStorage.setItem("scoresArray", JSON.stringify(scoresArray));

The issue that I would see occurring with how you're storing scores is that
each person has a win, loss, and tie counter, so you'll need to go through
additional steps. In my app, all I ever tracked was someone's initials and
their score on the quiz, it didn't take into account wins, losses, and
ties. So you'll need to iterate through the array and check if an
individual's score already exists, and then only update that specific
score. Else, you'll push a new record. In the above examples, I gave you
two ways of making the array based on how you're storing it now in
localStorage. However, you could also make objects. something like:

const score = {
      name: "person's name",
      scores: {
            wins: 0,
            losses: 0,
            ties: 0,
      }
}

and have these objects stored in the array instead. and then you'd
increment their score within each person's respective object.

Anyways, I probably gave you more information than you're asking for. All
you need to do to set an item in localstorage under one key is to first
create an array out of your records, and then set that array in
localstorage using localStorage.setItem("<key>", JSON.stringify(<array>));

If you have any other questions, let me know.
Best of luck!

**Comment by richjr93** [comment]
Hi, thank you for the reply.
First of all, I'm not really sure how to respond because I am really dumb to understand.

So if I'm not wrong, you suggest I change how I store the data in the localStorage first, combining all 3 records in an array instead of storing them separately. Is that right?

Anyway, I will show how the code is stored if it could help.

**key: name**
let userName = data.uniqueId
    var existing = localStorage.getItem(userName);
        if (existing != null && !isNaN(existing)) {
            var winStreak = parseInt(existing);
        } else {
            var winStreak = 0;
        }
        ++winStreak;
        localStorage.setItem(userName, winStreak);

**key: name_LOSE**
let userNameLOSE = data.uniqueId + "_LOSE";
    var existingLOSE = localStorage.getItem(userNameLOSE);
        if (existingLOSE != null && !isNaN(existingLOSE)) {
            var LOSE = parseInt(existingLOSE);
        } else {
            var LOSE = 0;
        }
        LOSE = LOSE + giftTotal;
        localStorage.setItem(userNameLOSE, LOSE);

**key: name_TIE**
let userNameTIE = data.uniqueId + "_TIE";
    var existingTIE = localStorage.getItem(userNameTIE);
        if (existingTIE != null && !isNaN(existingTIE)) {
            var TIE = parseInt(existingTIE);
        } else {
            var TIE = 0;
        }
        TIE = Math.floor(TIE + (giftTotal / 100 * 10));
        localStorage.setItem(userNameTIE, TIE);

So those are how the data is stored, it basically checks the current names whether it exists, if it does, it will add value to the existing name, otherwise, it will just create a new one. The userName is taken from data.uniqueId that's captured from whichever users entered the game. For the 2nd and 3rd sets of code, I just simply add a string to the userName, "_LOSE" and "_TIE" in order to differentiate the 3 categories, so the first one without addition is for the win. The giftTotal there is just a variable that contains numbers, just for the calculation.

As I mentioned before, I already have thousands of keys and values in my localStorage consisting of the 3 categories. It would be great if there's an easy way to convert them into an array. It could also reduce the number of rows used in localStorage.

Otherwise, I was wondering if I could just display the high scores from my current storing system? So for now, just retrieve the value from one of the 3 categories, maybe just from the win record? I'll then just do another one if I want to show the leaderboard for the other 2.

Thanks!

**Comment by RichardZhang01** [comment]
I've written a short piece of code with a hopefully understandable rundown
of each line of code. You should be able to copy and paste this into your
own code, or just use it as reference. I believe everything works, but I
did not actually test it since I don't have anything for a user to interact
with.

// classes are like blueprints that generate an object
// this class will create a new object with the name set to the name that
you pass to the constructor
class User {
  constructor(name) {
    this.name = name;
    this.ties = 0;
    this.wins = 0;
    this.losses = 0;
  }
}

// The way I think you want this implemented (a single array in
localStorage) would require you to
// set and get this single array to/from localStorage. We first get from
localStorage. If it doesn't
// exist yet then scoresArray will be initialized to an empty array. Note,
you can change the names here
// to whatever you want. This array will be stored in localStorage under
the key 'scores'. Also note
// the JSON.parse method. LocalStorage will only accept strings for the
value. We have to first convert our
// array into a string before storing it into localStorage (this will be
done further down in the code). This
// also means we have to convert that string back into an array when
retrieving it from localStorage which is
// what JSON.parse does here.
const scoresArray = JSON.parse(localStorage.getItem("scores")) || [];

// we can still use your userName variable here that comes from your game.
We'll use this to identify if our
// array already holds a record belonging to the user.
const userName = data.uniqueId;

// Not sure how you're tracking if the outcome of the game was a win or
loss or tie, but I have this arbitrary
// variable here that tracks what it is. I'll use this variable below, but
you can change this to how you've been tracking
// wins/losses/ties.
// Note that for this variable, it can only be a string: "WIN" | "LOSS" |
"TIE"
const gameOutcome = data.gameOutcome;

// To find if the user already exists in the array, you can use the
findIndex method. This method will go through
// the array and look for a record that has a name equal to the userName of
the player. If the individual exists, then
// userIndex will be set to the index of the user. If not, it will be -1.
const userIndex = scoresArray.findIndex((user) => user.name === userName);

// You can do this in any order but I would handle the case where the user
doesn't exist in our array first.
if (userIndex === -1) {
  // we make a new object from our class that's defined above
  // for example, if userName = "John", then the object would look like:
  // {
  //     name: "John",
  //     ties: 0,
  //     wins: 0,
  //     losses: 0,
  // }
  const newUser = new User(userName);

  // I'm guessing you want to increment one of the counters at this point
as well. There are many different ways to do this
  // I'll be using that gameOutcome variable I declared earlier.
  if (gameOutcome === "WIN") newUser.wins += 1;
  else if (gameOutcome === "LOSS") newUser.losses += 1;
  else newUser.ties += 1;

  // Finally, you can add this new newUser object to the array
  scoresArray.push(newUser);
} else {
  // The else case will handle if we've found the user in our array

  // Again, we'll be checking if the outcome was a win, a loss, or a tie,
and then incrementing the respective counter
  if (gameOutcome === "WIN") scoresArray[userIndex].wins += 1;
  else if (gameOutcome === "LOSS") scoresArray[userIndex].losses += 1;
  else scoresArray[userIndex].ties += 1;
}

// finally we send our array to localStorage
// To reiterate, localStorage only accepts strings for the value. So we
have to stringify the array first before setting it in
// localStorage
localStorage.setItem("scores", JSON.stringify(scoresArray));

**Comment by richjr93** [comment]
Thank you very much for your time. I really appreciate your help. I think the best way for me to really understand this is if it happens in real-time with my real project code but not sure how to do that and most importantly if only you have the time to entertain some noobies 😅.

Anyway, it's fine. I'm thankful enough for your help. At least I already have something that I could start with, thanks to you. Hopefully, I can figure this out. Thank you very much for the help, really appreciate it!

**Comment by RichardZhang01** [comment]
No problem, glad to help. It is definitely difficult starting out, and
doubly difficult when we're just exchanging ideas without, as you said,
working through your project in real-time with your actual code. If you
wanted to, I wouldn't mind looking at your code with you, either through
zoom or discord. Up to you though.

All the best!

**Comment by richjr93** [comment]
Oh really, thank you very much.
